spring:  
  application:
    name: techannotation-booking-service-mvc 

# turn off the security on the actuator end points as this is a demo app
#security:
#  basic:
#    enabled: false    

booking-service-dao:
  url: http://booking-service-dao-project-2.1d35.starter-us-east-1.openshiftapps.com/